#mysql:
#  addr: 127.0.0.1
#  username: root
#  password: root
#  port: 3306
#  database: test
#
#redis:
#  addr: 127.0.0.1
#  port: 6379
#  password: root
#  db: 0

#server:
#  addr: 0.0.0.0
#  port: 8081
#
#block:
#  - 127.0.0.1/24

app:
  - name: vles
    tls:
      cert: /root/p.cert
      key: /root/p.key
    listen:
      addr:
        - 0.0.0.0
      port:
        - 8081
    hosts:
      - abc.com
    path:
      - path: "/download"
        bind: test
    proxy:
      - name: test
        type: http
        addr: "http://127.0.0.1:8901"
        header:
          - key: X-Forwarded-For
            value: $remote_ip
    block:
      - 127.0.0.1/24
  - name: fileserver
    listen:
      addr:
        - 0.0.0.0
      port:
        - 8081
    hosts:
      - file.com
#   路径匹配
    path:
      - path: "/"
        bind: file
#   文件服务器
    filebrowser:
      - name: file
        root: "/root/file/"
